site_name: LASSO Proximal Gradient Method
docs_dir: src/notebooks

theme:
  name: material

nav:
  - LASSO: LASSO.md

site_url: https://avin-mo.github.io/LASSO-proximal-gradient-method/
use_directory_urls: false
